# Copied from https://github.com/rerun-io/rerun_template
# Disabled since this contains a lot of non-conforming code from the original repository
on: []

name: C++

jobs:
  python-check:
    name: Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.5.2
        with:
          pixi-version: v0.19.0
          cache: true

      - run: pixi run py-fmt-check

      - run: pixi run py-lint
